service: sls-az-func-rest-api
provider:
  name: azure
  location: East US
  runtime: nodejs12
plugins:
  - serverless-azure-functions
package:
  exclude:
    - localsettings.json
    - .vscode/**
functions:
  issues:
    handler: src/handlers/issues.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
  pulls:
    handler: src/handlers/pulls.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous